# Generated by Django 5.2.15 on 2026-06-24 05:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('score_complete', 'Score Complete'), ('score_failed', 'Score Failed'), ('streak_update', 'Streak Update'), ('subscription_change', 'Subscription Change'), ('achievement', 'Achievement'), ('system', 'System Message'), ('pdf_complete', 'PDF Export Complete'), ('pdf_failed', 'PDF Export Failed')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
