# Generated by Django 5.2.15 on 2026-06-13 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('score_complete', 'Score Complete'), ('score_failed', 'Score Failed'), ('streak_update', 'Streak Update'), ('subscription_change', 'Subscription Change'), ('achievement', 'Achievement'), ('system', 'System Message'), ('pdf_complete', 'PDF Export Complete'), ('pdf_failed', 'PDF Export Failed')], max_length=30),
        ),
    ]
