# Generated by Django 5.2.15 on 2026-06-29 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='Thời điểm notification hết hạn tương tác (e.g. PDF download link 1h)', null=True),
        ),
    ]
