# Generated by Django 5.2.9 on 2026-05-24 18:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EnWord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("word", models.CharField(db_index=True, max_length=100, unique=True)),
                ("ipa", models.CharField(blank=True, max_length=100)),
                ("translation_vi", models.TextField()),
                ("part_of_speech", models.JSONField(default=list)),
                (
                    "cefr_level",
                    models.CharField(blank=True, db_index=True, max_length=10),
                ),
                ("audio_url", models.URLField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name="EnExample",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("english", models.TextField()),
                ("vietnamese", models.TextField()),
                ("audio_url", models.URLField(blank=True, max_length=500)),
                (
                    "word",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="examples",
                        to="dictionary_en.enword",
                    ),
                ),
            ],
        ),
    ]
