# Generated by Django 5.2.15 on 2026-06-25 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary_en', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enword',
            name='image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
