# Generated by Django 5.2.15 on 2026-06-26 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary_en', '0002_enword_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='enword',
            name='core_inventory_1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='enword',
            name='core_inventory_2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='enword',
            name='definitions',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='enword',
            name='image_caption',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='enword',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='enword',
            name='threshold',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='enword',
            name='id',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='enword',
            name='part_of_speech',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='enword',
            name='translation_vi',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='enword',
            name='word',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='enword',
            unique_together={('word', 'part_of_speech')},
        ),
    ]
