# Generated by Django 5.2.15 on 2026-06-26 18:29

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary_en', '0003_enword_core_inventory_1_enword_core_inventory_2_and_more'),
    ]

    operations = [
        TrigramExtension(),
        migrations.AddField(
            model_name='enexample',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='enexample',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='enexample_search_vector_gin'),
        ),
        migrations.AddIndex(
            model_name='enexample',
            index=django.contrib.postgres.indexes.GinIndex(fields=['vietnamese'], name='en_matching_vi_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
    ]
