# Generated by Django 5.2.15 on 2026-06-26 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary_en', '0004_enexample_search_vector_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enword',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='enword',
            name='part_of_speech',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='enword',
            name='word',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
