# Generated by Django 5.2.15 on 2026-06-24 05:40

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_date', models.DateField(default=django.utils.timezone.now)),
                ('is_target_met', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DailyTarget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_words', models.IntegerField(default=10)),
                ('target_duration', models.IntegerField(default=15)),
                ('target_type', models.CharField(default='words', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StudyHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('study_date', models.DateField(default=django.utils.timezone.now)),
                ('vocabulary_learned', models.IntegerField(default=0)),
                ('pronunciation_accuracy', models.FloatField(default=0.0)),
                ('study_duration_seconds', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserStreak',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_streak', models.IntegerField(default=0)),
                ('max_streak', models.IntegerField(default=0)),
            ],
        ),
    ]
