# Generated by Django 5.2.15 on 2026-06-24 05:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gamification', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyactivity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dailytarget',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='daily_target', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studyhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_histories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userstreak',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='streak', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='dailyactivity',
            unique_together={('user', 'activity_date')},
        ),
        migrations.AlterUniqueTogether(
            name='studyhistory',
            unique_together={('user', 'study_date')},
        ),
    ]
