# Generated by Django 5.2.9 on 2026-05-24 18:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ZhWord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("word", models.CharField(db_index=True, max_length=50, unique=True)),
                ("traditional", models.CharField(blank=True, max_length=50)),
                ("pinyin", models.CharField(db_index=True, max_length=100)),
                ("toneless_pinyin", models.CharField(db_index=True, max_length=100)),
                (
                    "han_viet",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("translation_vi", models.TextField()),
                ("translation_en", models.TextField(blank=True)),
                ("part_of_speech", models.JSONField(default=list)),
                ("hsk_level", models.CharField(db_index=True, max_length=10)),
                ("radical", models.JSONField(default=list)),
                ("stroke_number", models.JSONField(default=list)),
                ("components", models.JSONField(default=list)),
                ("synonyms", models.JSONField(default=list)),
                ("antonyms", models.JSONField(default=list)),
                ("tags", models.JSONField(default=list)),
                ("word_frequency", models.FloatField(default=0.0)),
                ("popularity_rank", models.IntegerField(default=0)),
                ("audio_url", models.URLField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name="ZhExample",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("chinese", models.TextField()),
                ("pinyin", models.TextField()),
                ("vietnamese", models.TextField()),
                ("audio_url", models.URLField(blank=True, max_length=500)),
                (
                    "word",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="examples",
                        to="dictionary_zh.zhword",
                    ),
                ),
            ],
        ),
    ]
