# Generated by Django 5.2.9 on 2026-05-24 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dictionary_zh", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="zhword",
            name="word",
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
