# Generated by Django 5.2.14 on 2026-05-24 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary_zh', '0002_alter_zhword_word'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zhword',
            name='word',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
    ]
