# Generated by Django 5.2.14 on 2026-05-24 19:03

import django.contrib.postgres.indexes
from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension

class Migration(migrations.Migration):

    dependencies = [
        ('dictionary_zh', '0003_alter_zhword_word'),
    ]

    operations = [
        TrigramExtension(),
        migrations.AddIndex(
            model_name='zhword',
            index=django.contrib.postgres.indexes.GinIndex(fields=['translation_vi'], name='zhword_trans_vi_gin', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='zhword',
            index=django.contrib.postgres.indexes.GinIndex(fields=['han_viet'], name='zhword_hanviet_gin', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='zhword',
            index=django.contrib.postgres.indexes.GinIndex(fields=['toneless_pinyin'], name='zhword_tpinyin_gin', opclasses=['gin_trgm_ops']),
        ),
    ]
