# Generated by Django 5.2.14 on 2026-05-24 19:29

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary_zh', '0004_zhword_zhword_trans_vi_gin_zhword_zhword_hanviet_gin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zhexample',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='zhexample',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='zhexample_search_vector_gin'),
        ),
        migrations.RunSQL(
            sql='''
                CREATE TRIGGER zhexample_search_vector_update BEFORE INSERT OR UPDATE
                ON dictionary_zh_zhexample FOR EACH ROW EXECUTE FUNCTION
                tsvector_update_trigger(search_vector, 'pg_catalog.simple', chinese, vietnamese);
                
                -- Populate existing rows immediately
                UPDATE dictionary_zh_zhexample SET search_vector = to_tsvector('pg_catalog.simple', coalesce(chinese, '') || ' ' || coalesce(vietnamese, ''));
            ''',
            reverse_sql='''
                DROP TRIGGER IF EXISTS zhexample_search_vector_update ON dictionary_zh_zhexample;
            '''
        ),
    ]
