# Generated by Django 5.2.15 on 2026-06-13 17:20

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary_zh', '0005_zhexample_search_vector_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='zhexample',
            index=django.contrib.postgres.indexes.GinIndex(fields=['vietnamese'], name='zh_matching_vi_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
    ]
