# Generated by Django 5.2.15 on 2026-06-21 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary_zh', '0006_zhexample_zh_matching_vi_trgm_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zhword',
            name='word',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='zhword',
            unique_together={('word', 'pinyin', 'hsk_level')},
        ),
    ]
