# Generated by Django 5.2.15 on 2026-06-25 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary_zh', '0007_alter_zhword_word_alter_zhword_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='zhword',
            name='image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
