# Generated by Django 5.2.15 on 2026-06-26 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary_zh', '0008_zhword_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zhword',
            name='id',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
    ]
