# Generated by Django 5.2.14 on 2026-05-06 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmenttask',
            name='details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessmenttask',
            name='target_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
