# Generated by Django 5.2.14 on 2026-05-13 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_assessmenttask_details_assessmenttask_target_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assessmenttask',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='assessmenttask',
            old_name='details',
            new_name='result_data',
        ),
        migrations.AddField(
            model_name='assessmenttask',
            name='error_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='assessmenttask',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('zh', 'Chinese')], default='en', max_length=5),
        ),
        migrations.AlterField(
            model_name='assessmenttask',
            name='target_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
