# Generated by Django 5.2.14 on 2026-06-12 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0004_assessmenttask_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmenttask',
            name='queue_name',
            field=models.CharField(choices=[('queue_paid', 'Paid Queue'), ('queue_free', 'Free Queue'), ('queue_guest', 'Guest Queue')], db_index=True, default='queue_guest', help_text='The physical queue in Redis/Celery that this task is routed to', max_length=20),
        ),
    ]
