# Generated by Django 5.2.15 on 2026-06-27 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0005_assessmenttask_queue_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmenttask',
            name='refund_status',
            field=models.CharField(choices=[('NOT_REFUNDED', 'Not Refunded'), ('PENDING', 'Pending Refund'), ('SUCCESS', 'Refunded Successfully'), ('FAILED', 'Refund Failed')], db_index=True, default='NOT_REFUNDED', max_length=20),
        ),
    ]
