# Generated by Django 5.2.15 on 2026-06-24 05:40

import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tier', models.CharField(max_length=20)),
                ('action', models.CharField(choices=[('UPGRADE', 'Nâng cấp'), ('RENEW', 'Gia hạn'), ('DOWNGRADE', 'Hạ cấp'), ('CANCEL', 'Hủy gói')], max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tier', models.CharField(choices=[('Free', 'Free'), ('Plus', 'Plus'), ('Premium', 'Premium'), ('Pro', 'Pro')], max_length=20, unique=True)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Giá gốc của gói', max_digits=10)),
                ('vat', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Tỷ lệ thuế VAT (%)', max_digits=5)),
                ('description', models.TextField(blank=True, default='', help_text='Mô tả quyền lợi của gói')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tier', models.CharField(choices=[('Free', 'Free'), ('Plus', 'Plus'), ('Premium', 'Premium'), ('Pro', 'Pro')], default='Free', max_length=20)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Giá gốc lưu tại thời điểm thanh toán', max_digits=10)),
                ('vat', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Tỷ lệ thuế VAT (%) lưu tại thời điểm thanh toán', max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='VolumeLimitConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tier', models.CharField(choices=[('Guest', 'Guest'), ('Free', 'Free'), ('Plus', 'Plus'), ('Premium', 'Premium'), ('Pro', 'Pro')], max_length=20, unique=True)),
                ('mb_per_minute', models.PositiveIntegerField(default=2)),
                ('mb_per_hour', models.PositiveIntegerField(default=20)),
                ('mb_per_day', models.PositiveIntegerField(default=100)),
                ('pdf_daily_limit', models.PositiveIntegerField(default=2, help_text='Số lần xuất PDF tối đa mỗi ngày')),
                ('pdf_word_limit', models.PositiveIntegerField(default=10, help_text='Số từ vựng tối đa mỗi file PDF')),
            ],
        ),
    ]
