# Generated by Django 5.2.14 on 2026-05-29 18:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='tier',
            field=models.CharField(choices=[('Free', 'Free'), ('Plus', 'Plus'), ('Premium', 'Premium'), ('Pro', 'Pro')], default='Free', max_length=20),
        ),
        migrations.CreateModel(
            name='SubscriptionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(max_length=20)),
                ('action', models.CharField(choices=[('UPGRADE', 'Nâng cấp'), ('RENEW', 'Gia hạn'), ('DOWNGRADE', 'Hạ cấp'), ('CANCEL', 'Hủy gói')], max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
