# Generated by Django 5.2.14 on 2026-06-07 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_alter_usersubscription_tier_subscriptionhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolumeLimitConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('Free', 'Free'), ('Plus', 'Plus'), ('Premium', 'Premium'), ('Pro', 'Pro')], max_length=20, unique=True)),
                ('mb_per_minute', models.PositiveIntegerField(default=2)),
                ('mb_per_hour', models.PositiveIntegerField(default=20)),
                ('mb_per_day', models.PositiveIntegerField(default=100)),
            ],
        ),
    ]
