# Generated by Django 5.2.15 on 2026-06-28 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='pending_downgrade_tier',
            field=models.CharField(blank=True, choices=[('Free', 'Free'), ('Plus', 'Plus'), ('Pro', 'Pro'), ('Premium', 'Premium')], help_text='Gói sẽ chuyển xuống khi hết hạn end_date', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='tier',
            field=models.CharField(choices=[('Free', 'Free'), ('Plus', 'Plus'), ('Pro', 'Pro'), ('Premium', 'Premium')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='tier',
            field=models.CharField(choices=[('Free', 'Free'), ('Plus', 'Plus'), ('Pro', 'Pro'), ('Premium', 'Premium')], default='Free', max_length=20),
        ),
    ]
