# Generated by Django 5.2.14 on 2026-06-10 15:11

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_volumelimitconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('Free', 'Free'), ('Plus', 'Plus'), ('Premium', 'Premium'), ('Pro', 'Pro')], max_length=20, unique=True)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Giá gốc của gói', max_digits=10)),
                ('vat', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Tỷ lệ thuế VAT (%)', max_digits=5)),
                ('description', models.TextField(blank=True, default='', help_text='Mô tả quyền lợi của gói')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Giá gốc lưu tại thời điểm thanh toán', max_digits=10),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='vat',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Tỷ lệ thuế VAT (%) lưu tại thời điểm thanh toán', max_digits=5),
        ),
        migrations.AlterField(
            model_name='volumelimitconfig',
            name='tier',
            field=models.CharField(choices=[('Guest', 'Guest'), ('Free', 'Free'), ('Plus', 'Plus'), ('Premium', 'Premium'), ('Pro', 'Pro')], max_length=20, unique=True),
        ),
    ]
