# Generated by Django 5.2.15 on 2026-06-29 05:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_usersubscription_pending_downgrade_tier_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_tier', models.CharField(help_text='Gói muốn nâng cấp lên', max_length=20)),
                ('amount', models.DecimalField(decimal_places=0, help_text='Số tiền cần thanh toán (VNĐ, không lẻ)', max_digits=12)),
                ('order_code', models.CharField(db_index=True, help_text='Mã đơn hàng unique, VD: CNEN-abc12345', max_length=50, unique=True)),
                ('transfer_content', models.CharField(help_text='Nội dung chuyển khoản đầy đủ user cần ghi', max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Chờ thanh toán'), ('PAID', 'Đã thanh toán'), ('EXPIRED', 'Hết hạn'), ('FAILED', 'Thất bại')], default='PENDING', max_length=10)),
                ('sepay_transaction_id', models.CharField(blank=True, default='', max_length=100)),
                ('bank_reference', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='Thời điểm đơn hàng hết hạn nếu chưa thanh toán')),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
