# Generated by Django 5.2.15 on 2026-06-13 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_subscriptionplan_usersubscription_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='volumelimitconfig',
            name='pdf_daily_limit',
            field=models.PositiveIntegerField(default=2, help_text='Số lần xuất PDF tối đa mỗi ngày'),
        ),
        migrations.AddField(
            model_name='volumelimitconfig',
            name='pdf_word_limit',
            field=models.PositiveIntegerField(default=10, help_text='Số từ vựng tối đa mỗi file PDF'),
        ),
    ]
