# Generated by Django 5.2.15 on 2026-06-25 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dictionary_en', '0002_enword_image_url'),
        ('dictionary_zh', '0008_zhword_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZhEnMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en_translation', models.CharField(help_text='Từ khóa tiếng Anh sạch dùng làm Prompt cho AI (sanitized keyword)', max_length=255)),
                ('en_word', models.ForeignKey(blank=True, help_text='Từ vựng tiếng Anh tương ứng (nullable nếu chưa nạp vào DB)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zh_mappings', to='dictionary_en.enword')),
                ('zh_word', models.ForeignKey(help_text='Từ vựng tiếng Trung gốc', on_delete=django.db.models.deletion.CASCADE, related_name='en_mappings', to='dictionary_zh.zhword')),
            ],
            options={
                'verbose_name': 'ZH-EN Mapping',
                'verbose_name_plural': 'ZH-EN Mappings',
                'indexes': [models.Index(fields=['zh_word'], name='media_zhenm_zh_word_957fa9_idx'), models.Index(fields=['en_word'], name='media_zhenm_en_word_f6dd3c_idx')],
                'unique_together': {('zh_word', 'en_translation')},
            },
        ),
    ]
