# Generated by Django 5.2.15 on 2026-06-26 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary_en', '0003_enword_core_inventory_1_enword_core_inventory_2_and_more'),
        ('dictionary_zh', '0009_alter_zhword_id'),
        ('media', '0001_zh_en_mapping'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='zhenmapping',
            unique_together={('zh_word', 'en_word')},
        ),
        migrations.AddField(
            model_name='zhenmapping',
            name='image_caption',
            field=models.TextField(blank=True, help_text='Mô tả hình ảnh tiếng Anh làm Prompt cho AI sinh ảnh (image caption)'),
        ),
        migrations.RemoveField(
            model_name='zhenmapping',
            name='en_translation',
        ),
    ]
