# Generated by Django 5.2.14 on 2026-05-18 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_id', models.CharField(help_text='ID duy nhất, VD: HSK1_NEW_UUID_001', max_length=100, unique=True)),
                ('exam_name', models.CharField(help_text='Tên bài thi', max_length=500)),
                ('exam_version', models.CharField(default='1.0', max_length=20)),
                ('level', models.CharField(help_text='VD: HSK 1, HSK 2, ...', max_length=20)),
                ('total_questions', models.IntegerField(default=0)),
                ('total_time_minutes', models.IntegerField(default=0, help_text='Thời gian thi (phút)')),
                ('total_score', models.IntegerField(default=0, help_text='Tổng điểm tối đa')),
                ('passing_score', models.IntegerField(default=0, help_text='Điểm đạt')),
                ('allow_resume', models.BooleanField(default=True, help_text='Cho phép tiếp tục thi')),
                ('max_attempts', models.IntegerField(default=-1, help_text='-1 = không giới hạn')),
                ('shuffle_questions', models.BooleanField(default=False)),
                ('shuffle_options', models.BooleanField(default=False)),
                ('show_explanation_after', models.CharField(default='exam_submitted', help_text='Thời điểm hiển thị giải thích: exam_submitted, each_question, never', max_length=50)),
                ('status', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'exams_exam',
                'ordering': ['level', 'exam_id'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_id', models.CharField(help_text='VD: sec_listening_01', max_length=100)),
                ('section_name', models.CharField(choices=[('Listening', 'Listening'), ('Reading', 'Reading'), ('Writing', 'Writing')], help_text='Listening / Reading / Writing', max_length=50)),
                ('part_number', models.IntegerField(help_text='Số thứ tự phần trong kỹ năng')),
                ('instruction', models.TextField(blank=True, default='', help_text='Hướng dẫn bằng tiếng Trung, VD: 第一部分：听录音，判断对错')),
                ('section_audio_url', models.URLField(blank=True, default='', help_text='URL audio chung cho cả section', max_length=500)),
                ('ordering', models.IntegerField(default=0, help_text='Thứ tự hiển thị')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='exams.exam')),
            ],
            options={
                'db_table': 'exams_section',
                'ordering': ['exam', 'ordering', 'part_number'],
                'unique_together': {('exam', 'section_id')},
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.CharField(help_text='VD: q_listen_001', max_length=100)),
                ('question_type', models.CharField(choices=[('true_false', 'True/False - Đúng Sai'), ('multiple_choice', 'Multiple Choice - Trắc nghiệm'), ('fill_blank', 'Fill in Blank - Điền từ'), ('matching', 'Matching - Nối'), ('ordering', 'Ordering - Sắp xếp')], max_length=30)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=20)),
                ('points', models.IntegerField(default=5, help_text='Điểm cho câu hỏi này')),
                ('tags', models.JSONField(blank=True, default=list, help_text='VD: ["listening", "vocabulary", "noun"]')),
                ('audio_url', models.URLField(blank=True, default='', help_text='URL file audio riêng cho câu hỏi', max_length=500)),
                ('audio_start_time', models.CharField(blank=True, default='', help_text='Thời điểm bắt đầu trong audio chung (VD: 00:01:30)', max_length=20)),
                ('audio_end_time', models.CharField(blank=True, default='', help_text='Thời điểm kết thúc trong audio chung', max_length=20)),
                ('audio_script', models.TextField(blank=True, default='', help_text='Nội dung đọc, VD: 医院。 (Yīyuàn)')),
                ('question_text', models.TextField(blank=True, default='', help_text='Câu hỏi hiển thị, VD: 小猫在哪儿？')),
                ('image_url', models.URLField(blank=True, default='', help_text='URL hình ảnh đề bài', max_length=500)),
                ('image_description', models.TextField(blank=True, default='', help_text='Mô tả hình ảnh, VD: A hospital building.')),
                ('correct_answer', models.CharField(help_text='ID đáp án đúng, VD: opt_True, opt_A', max_length=50)),
                ('explanation', models.TextField(blank=True, default='', help_text='Giải thích đáp án')),
                ('ordering', models.IntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exams.section')),
            ],
            options={
                'db_table': 'exams_question',
                'ordering': ['section', 'ordering'],
                'unique_together': {('section', 'question_id')},
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_id', models.CharField(help_text='VD: opt_True, opt_A, opt_B, opt_C', max_length=50)),
                ('text', models.TextField(blank=True, default='', help_text='Nội dung text, VD: 椅子下面')),
                ('image_url', models.URLField(blank=True, default='', help_text='URL hình ảnh option', max_length=500)),
                ('image_description', models.TextField(blank=True, default='', help_text='Mô tả hình ảnh option')),
                ('ordering', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='exams.question')),
            ],
            options={
                'db_table': 'exams_option',
                'ordering': ['question', 'ordering'],
                'unique_together': {('question', 'option_id')},
            },
        ),
    ]
