# Generated by Django 5.2.14 on 2026-05-20 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('zh', 'Chinese')], default='zh', help_text='Ngôn ngữ của đề thi (en/zh)', max_length=5),
        ),
    ]
