# Generated by Django 5.2.15 on 2026-06-26 21:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('image', 'Ảnh sai/không phù hợp'), ('translation', 'Bản dịch sai'), ('pinyin', 'Pinyin/IPA sai'), ('example', 'Ví dụ sai'), ('exam_question', 'Câu hỏi thi sai'), ('audio', 'Audio sai/hỏng'), ('other', 'Lỗi khác')], max_length=20)),
                ('content_type', models.CharField(choices=[('zh_word', 'ZhWord'), ('en_word', 'EnWord'), ('zh_example', 'ZhExample'), ('en_example', 'EnExample'), ('exam_question', 'Exam Question'), ('exam_option', 'Exam Option')], max_length=20)),
                ('object_id', models.UUIDField(db_index=True)),
                ('guest_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('reason', models.TextField(blank=True)),
                ('suggested_correction', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Chờ xử lý'), ('reviewing', 'Đang xem xét'), ('resolved', 'Đã sửa'), ('dismissed', 'Bỏ qua')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reports_contentreport',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('reporter__isnull', False)), fields=('content_type', 'object_id', 'report_type', 'reporter'), name='unique_authenticated_user_report'), models.UniqueConstraint(condition=models.Q(('reporter__isnull', True), models.Q(('guest_id', ''), _negated=True)), fields=('content_type', 'object_id', 'report_type', 'guest_id'), name='unique_guest_user_report')],
            },
        ),
    ]
