# Generated by Django 5.2.15 on 2026-06-26 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentreport',
            name='object_id',
            field=models.CharField(db_index=True, max_length=64),
        ),
    ]
