# Generated by Django 5.2.15 on 2026-06-27 12:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_contentreport_object_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('guest_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('feature_area', models.CharField(choices=[('dictionary', 'Tra từ & Học tập'), ('speaking', 'Luyện nói'), ('writing', 'Luyện viết'), ('exam', 'Luyện thi'), ('notes', 'Sổ tay'), ('translate', 'Dịch thông minh'), ('ui_ux', 'Giao diện & Trải nghiệm'), ('other', 'Khác')], default='other', max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Chờ xử lý'), ('reviewing', 'Đang xem xét'), ('planned', 'Đã lên kế hoạch'), ('implemented', 'Đã triển khai'), ('dismissed', 'Bỏ qua')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feature_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reports_featurereport',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('guest_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('guest_name', models.CharField(blank=True, default='', max_length=100)),
                ('guest_email', models.EmailField(blank=True, db_index=True, default='', max_length=254)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('bug', 'Báo cáo lỗi hệ thống'), ('billing', 'Thanh toán & Đăng ký'), ('account', 'Tài khoản & Bảo mật'), ('other', 'Hỗ trợ khác')], default='other', max_length=30)),
                ('priority', models.CharField(choices=[('low', 'Thấp'), ('medium', 'Trung bình'), ('high', 'Cao'), ('urgent', 'Khẩn cấp')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Đang mở'), ('in_progress', 'Đang xử lý'), ('resolved', 'Đã giải quyết'), ('closed', 'Đã đóng')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reports_supportrequest',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment_text', models.TextField()),
                ('is_internal', models.BooleanField(default=False, help_text='True = Ghi chú nội bộ giữa các Admin; False = Công khai cho người dùng')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_comments', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='reports.supportrequest')),
            ],
            options={
                'verbose_name': 'Ticket Comment',
                'verbose_name_plural': 'Ticket Comments',
                'db_table': 'reports_ticketcomment',
                'ordering': ['created_at'],
            },
        ),
    ]
