# Generated by Django 5.2.15 on 2026-06-30 17:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlashcardExercise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('word', models.CharField(db_index=True, max_length=255, verbose_name='Từ vựng gốc')),
                ('lang', models.CharField(choices=[('zh', 'Chinese'), ('en', 'English')], default='zh', max_length=10, verbose_name='Ngôn ngữ')),
                ('exercise_type', models.CharField(choices=[('reading', 'Reading Quiz'), ('listening', 'Listening Quiz')], max_length=20, verbose_name='Loại bài tập')),
                ('content', models.JSONField(verbose_name='Nội dung bài tập')),
                ('audio_url', models.URLField(blank=True, default='', verbose_name='Audio URL (Listening)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Flashcard Exercise',
                'verbose_name_plural': 'Flashcard Exercises',
                'indexes': [models.Index(fields=['word', 'lang'], name='flashcard_e_word_c52873_idx')],
                'unique_together': {('word', 'lang', 'exercise_type')},
            },
        ),
    ]
