# Generated by Django 5.2.15 on 2026-06-30 17:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard_exercises', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFlashcardHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('word', models.CharField(db_index=True, max_length=255)),
                ('lang', models.CharField(default='zh', max_length=10)),
                ('exercise_type', models.CharField(max_length=20)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'User Flashcard History',
                'verbose_name_plural': 'User Flashcard Histories',
                'ordering': ['completed_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='flashcardexercise',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='flashcardexercise',
            index=models.Index(fields=['word', 'lang', 'exercise_type'], name='flashcard_e_word_bf2f43_idx'),
        ),
        migrations.AddField(
            model_name='userflashcardhistory',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_history', to='flashcard_exercises.flashcardexercise'),
        ),
        migrations.AddField(
            model_name='userflashcardhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcard_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='userflashcardhistory',
            index=models.Index(fields=['user', 'word', 'lang', 'exercise_type'], name='flashcard_e_user_id_f5b6a3_idx'),
        ),
    ]
