# Generated by Django 5.2.15 on 2026-06-26 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebook',
            name='lang',
            field=models.CharField(choices=[('zh', 'Chinese'), ('en', 'English')], default='zh', max_length=10, verbose_name='Ngôn ngữ'),
        ),
    ]
