# Generated by Django 5.2.15 on 2026-06-30 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_notebook_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='is_mastered',
            field=models.BooleanField(default=False, verbose_name='Đã thuộc'),
        ),
    ]
